// The framebuffer quad: the studio's picture drawn into a rectangle of the window.
// Generated by sokol-shdc into blit.h for every backend it supports.

@vs blit_vs
layout(binding=0) uniform vs_params {
    vec2 rect_pos;      // top-left corner, in window pixels
    vec2 rect_size;     // in window pixels
    vec2 resolution;    // the window, in pixels
};

in vec2 pos;            // the unit quad, 0..1
in vec2 uv;

out vec2 uv_out;

void main() {
    vec2 px = rect_pos + pos * rect_size;
    vec2 ndc = (px / resolution) * 2.0 - 1.0;
    gl_Position = vec4(ndc.x, -ndc.y, 0.0, 1.0);
    uv_out = uv;
}
@end

@fs blit_fs
layout(binding=0) uniform texture2D tex;
layout(binding=0) uniform sampler smp;

in vec2 uv_out;
out vec4 frag_color;

void main() {
    frag_color = texture(sampler2D(tex, smp), uv_out);
}
@end

@program blit blit_vs blit_fs
