// The quad every picture is drawn with: the studio's framebuffer, and the
// control sprites cut out of their sheet.
// Generated by sokol-shdc into blit.h for every backend it supports.

@vs blit_vs
layout(binding=0) uniform vs_params {
    vec2 rect_pos;      // where, in window pixels
    vec2 rect_size;
    vec2 resolution;    // the window, in pixels
    vec2 uv_pos;        // what, in texture pixels
    vec2 uv_size;
    vec2 tex_size;
};

in vec2 pos;            // the unit quad, 0..1
in vec2 uv;

out vec2 uv_out;

void main() {
    vec2 px = rect_pos + pos * rect_size;
    vec2 ndc = (px / resolution) * 2.0 - 1.0;
    gl_Position = vec4(ndc.x, -ndc.y, 0.0, 1.0);
    uv_out = (uv_pos + uv * uv_size) / tex_size;
}
@end

@fs blit_fs
layout(binding=0) uniform texture2D tex;
layout(binding=0) uniform sampler smp;

in vec2 uv_out;
out vec4 frag_color;

void main() {
    frag_color = texture(sampler2D(tex, smp), uv_out);
}
@end

@program blit blit_vs blit_fs
