#!/usr/bin/env python3
"""
Script to embed HTML template files as C byte arrays in the TIC-80 binary
"""

import os
import sys

def file_to_c_array(input_file, var_name):
    """Convert a file to a C byte array definition"""
    with open(input_file, 'rb') as f:
        data = f.read()

    # Create the C array definition
    lines = []
    lines.append(f"// Embedded file: {os.path.basename(input_file)}")
    lines.append(f"static const unsigned char {var_name}[] = {{")

    # Format bytes, 16 per line
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f"    {hex_bytes},")

    lines.append("};")
    lines.append(f"static const size_t {var_name}_size = {len(data)};")
    lines.append("")

    return '\n'.join(lines)

def main():
    if len(sys.argv) != 2:
        print("Usage: embed_html.py <output_file>")
        sys.exit(1)

    output_file = sys.argv[1]

    # Files to embed
    html_template = "build/html/export.html"
    js_runtime = "build/bin/tic80.js"
    wasm_runtime = "build/bin/tic80.wasm"

    # Check if files exist
    missing_files = []
    if not os.path.exists(html_template):
        missing_files.append(html_template)
    if not os.path.exists(js_runtime):
        missing_files.append(js_runtime)
    if not os.path.exists(wasm_runtime):
        missing_files.append(wasm_runtime)

    if missing_files:
        print(f"Error: Missing required files: {', '.join(missing_files)}")
        sys.exit(1)

    # Generate the header file
    content = []
    content.append("// Auto-generated file - do not edit manually")
    content.append("// Generated by tools/embed_html.py")
    content.append("")
    content.append("#pragma once")
    content.append("")

    # Embed HTML template
    content.append(file_to_c_array(html_template, "embedded_html_template"))

    # Embed JavaScript runtime
    content.append(file_to_c_array(js_runtime, "embedded_tic80_js"))

    # Embed WASM runtime
    content.append(file_to_c_array(wasm_runtime, "embedded_tic80_wasm"))

    # Write the output file
    with open(output_file, 'w') as f:
        f.write('\n'.join(content))

    print(f"Generated {output_file} with embedded HTML templates")

if __name__ == "__main__":
    main()